server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      # 连接池配置
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 逻辑删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # mapper xml 文件路径
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT 配置
jwt:
  # JWT 密钥（生产环境请使用更复杂的密钥）
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  # Access Token 过期时间（15分钟）
  access-token-expiration: 900000
  # Refresh Token 过期时间（7天）
  refresh-token-expiration: 604800000
  # Token 前缀
  token-prefix: Bearer
  # Token Header
  token-header: Authorization

# 日志配置
logging:
  level:
    com.example.jwt: DEBUG
    com.example.jwt.mapper: DEBUG
#    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/jwt-demo.log

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 配置正确的URL路径，考虑context-path
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
  # 显示所有接口，包括需要认证的
  show-actuator: true

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized